
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Accounts.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Status of account
    /// </summary>
    public enum AccountDetailsStatus
    {
        [JsonProperty("OPEN")]
        Open,
        [JsonProperty("CLOSED")]
        Closed,
    }

    public static class AccountDetailsStatusExtension
    {
        public static string Value(this AccountDetailsStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AccountDetailsStatus ToEnum(this string value)
        {
            foreach(var field in typeof(AccountDetailsStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AccountDetailsStatus)
                    {
                        return (AccountDetailsStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AccountDetailsStatus");
        }
    }
}