
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Accounts.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Country code according to ISO Alpha-2
    /// </summary>
    public enum BankInfoCountry
    {
        [JsonProperty("FI")]
        Fi,
        [JsonProperty("SE")]
        Se,
        [JsonProperty("DK")]
        Dk,
        [JsonProperty("NO")]
        No,
    }

    public static class BankInfoCountryExtension
    {
        public static string Value(this BankInfoCountry value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static BankInfoCountry ToEnum(this string value)
        {
            foreach(var field in typeof(BankInfoCountry).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is BankInfoCountry)
                    {
                        return (BankInfoCountry)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum BankInfoCountry");
        }
    }
}