
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Accounts.Models.Shared
{
    using Accounts.Models.Shared;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Error response body
    /// </summary>
    public class ErrorPayload
    {

        /// <summary>
        /// More details on the occurred error
        /// </summary>
        [JsonProperty("failures")]
        public List<Failure>? Failures { get; set; }

        /// <summary>
        /// Original request information
        /// </summary>
        [JsonProperty("request")]
        public RequestEcho? Request { get; set; }
    }
}