
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Accounts.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Validation error
    /// </summary>
    public class Failure
    {

        /// <summary>
        /// Failure code
        /// </summary>
        [JsonProperty("code")]
        public string? Code { get; set; }

        /// <summary>
        /// Failure description
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// JSON path of the failing element if applicable
        /// </summary>
        [JsonProperty("path")]
        public string? Path { get; set; }

        /// <summary>
        /// Type of the validation error, e.g. NotNull
        /// </summary>
        [JsonProperty("type")]
        public string? Type { get; set; }
    }
}