
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Accounts.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Internal, technical account identifier
    /// </summary>
    public class IdV5toV4
    {

        /// <summary>
        /// Internal, technical account identifier - V4
        /// </summary>
        [JsonProperty("_id")]
        public string Id { get; set; } = default!;
    }
}