
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Accounts.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Context specific link (only GET supported)
    /// </summary>
    public class Link
    {

        /// <summary>
        /// Relative path to the linked resource
        /// </summary>
        [JsonProperty("href")]
        public string? Href { get; set; }

        /// <summary>
        /// Describes the nature of the link, e.g. &apos;details&apos; for a link to the detailed information of a listed resource.
        /// </summary>
        [JsonProperty("rel")]
        public string? Rel { get; set; }
    }
}