
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Accounts.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Details of paginated response
    /// </summary>
    public class Pagination
    {

        /// <summary>
        /// Resource listing may return a continuationKey if there&apos;s more results available. Request may be retried with the continuationKey, but otherwise same parameters, in order to get more results.
        /// </summary>
        [JsonProperty("continuation_key")]
        public string? ContinuationKey { get; set; }
    }
}