
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Accounts.Models.Shared
{
    using Newtonsoft.Json;
    
    /// <summary>
    /// Original request information
    /// </summary>
    public class RequestEcho
    {

        /// <summary>
        /// Original request url
        /// </summary>
        [JsonProperty("url")]
        public string? Url { get; set; }
    }
}