
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Accounts.Models.Shared
{
    using Accounts.Utils;
    
    public class Security
    {

        [SpeakeasyMetadata("security:scheme=true,type=oauth2,name=Authorization")]
        public string? DecoupledAuth { get; set; }

        [SpeakeasyMetadata("security:scheme=true,type=oauth2,name=Authorization")]
        public string? OAuth2 { get; set; }
    }
}