
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Accounts.Models.Shared
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// List of transactions
    /// </summary>
    public class TransactionList
    {

        /// <summary>
        /// HATEOAS inspired links: &apos;rel&apos; and &apos;href&apos;
        /// </summary>
        [JsonProperty("_links")]
        public List<Link>? Links { get; set; }

        /// <summary>
        /// Account number
        /// </summary>
        [JsonProperty("account_number")]
        public AccountNumber? AccountNumber { get; set; }

        /// <summary>
        /// Listed transactions
        /// </summary>
        [JsonProperty("transactions")]
        public List<Transaction>? Transactions { get; set; }
    }
}